services:
  frontend:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://localhost:8000}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev -- -H 0.0.0.0 -p 3000
